spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    # tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    # Absolute path
    # url: jdbc:h2:C:/projects/bootjava/restorant-voting/db/voting
    # tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/restorant-voting/db/voting
    # Relative path form current dir
    # url: jdbc:h2:./db/voting
    # Relative path from home
    # url: jdbc:h2:~/voting
    # tcp: jdbc:h2:tcp://localhost:9092/~/voting
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  data:
    rest:
      base-path: /api
      return-body-on-create: true


#  jackson:
 #   visibility:
  #    field: any
   #   getter: none
    #  setter: none
     # is-getter: none
